### ISSUE TITLE
no webqa-process-schemaorg.js in genie-toolkit/tool

### ISSUE THREAD

**Issue by allen880307** [stanford-oval/cs294-homework-workdir#2]
Excuse me, I have some problems when I make restaurents/schema.tt , I got an error message about :"make: *** No rule to make target '/usr/home/allen/Desktop/cs294-homework-workdir/genie-toolkit/tool/webqa-process-schemaorg.js', needed by 'restaurants/schema.org.tt'.  Stop." I have checked my absolutes path of the genie-toolkit in makefile, it's correct. And I found that there was no file named  webqa-process-schemaorg.js in genie-toolkit/tool that I git cloned. I would appreciate it if you could take a moment to help me, thanks.

**Comment by allen880307** [comment]
I solved this problems by git checkout to another branch that has the file I needed.

**Comment by gcampax** [comment]
Closing this.
